package com.harbour.ws.controller;

import com.harbour.ws.domain.cc.WarehouseObject;
import com.harbour.ws.domain.jsh.NeobulkBerthObject;
import com.harbour.ws.domain.jsh.NeobulkYard;
import com.harbour.ws.domain.jzx.*;
import com.harbour.ws.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

// 获取某一类对象实时基本数据
@RestController
public class GetObjectListInfo {

    @Autowired // 集装箱-移动设施-船舶-Y10
    private ContainerShipService containerShipService;
    @Autowired // 集装箱-固定设施-泊位-S01
    private ContainerBerthObjectService containerBerthObjectService;
    @Autowired // 集装箱-固定机械-岸桥-J01
    private QuayCraneObjectService quayCraneObjectService;
    @Autowired // 集装箱-固定机械-场桥-J02
    private YardCraneObjectService yardCraneObjectService;
    @Autowired // 集装箱-固定设施-堆场-S02-详细信息
    private ContainerYardObjectService containerYardObjectService;

    @Autowired // 件散货-固定设施-泊位-S01
    private NeobulkBerthObjectService neobulkBerthObjectService;
    @Autowired // 件散货-移动设施-船舶-Y10
    private NeobulkShipService neobulkShipService;
    @Autowired // 件散货-固定设施-堆场-S02
    private NeobulkYardService neobulkYardService;

    @Autowired // 两江仓储-固定设施-仓库-S04
    private WarehouseObjectService warehouseObjectService;

    @GetMapping("/getObjectListInfo")
    public String getObjectListInfo(@RequestParam String type) {
        StringBuffer sb = new StringBuffer();
        sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        sb.append("<Data>\n");
        sb.append("  <tableList>\n");
        if("all".equals(type)) { // 返回所有的基本信息
            // 集装箱-堆场
            List<ContainerYardObject> one;
            // 集装箱-场桥
            List<YardCraneObject> yardCraneObject;
            // 集装箱-泊位
            List<ContainerBerthObject> containerBerthObjects;
            // 集装箱-岸桥
            List<QuayCraneObject> quayCraneObject;

            try{
                one = containerYardObjectService.findAllJzx();
                yardCraneObject = yardCraneObjectService.findAllJzx();
                containerBerthObjects =  containerBerthObjectService.findAllJzx();
                quayCraneObject  = quayCraneObjectService.findAllJzx();
            }catch(Exception e){
                one = containerYardObjectService.findAllDc();
                yardCraneObject = yardCraneObjectService.findAllDc();
                containerBerthObjects =  containerBerthObjectService.findAllDc();
                quayCraneObject  = quayCraneObjectService.findAllDc();
            }
            //集装箱-堆场
            for (int j = 0;j < one.size();j++) {
                sb.append("    <rows>\n");
                sb.append("		  <th name=\"对象编码: \">"+one.get(j).getCode()+"</th>\n");
                sb.append("		  <th name=\"对象名称: \">"+one.get(j).getMc()+"</th>\n");
                sb.append("		  <th name=\"使用率: \">"+one.get(j).getRate()+"</th>\n");
                sb.append("		  <th name=\"总容量: \">"+one.get(j).getZrl()+"</th>\n");
                sb.append("		  <th name=\"使用量: \">"+one.get(j).getSyl()+"</th>\n");
                sb.append("		  <th name=\"剩余量: \">"+one.get(j).getSy()+"</th>\n");
                sb.append("		  <th name=\"重箱: \">"+one.get(j).getZx()+"</th>\n");
                sb.append("		  <th name=\"空箱: \">"+one.get(j).getKx()+"</th>\n");
                sb.append("		  <th name=\"内贸: \">"+one.get(j).getNm()+"</th>\n");
                sb.append("		  <th name=\"外贸: \">"+one.get(j).getWm()+"</th>\n");
                sb.append("		  <th name=\"出口: \">"+one.get(j).getCk()+"</th>\n");
                sb.append("		  <th name=\"进口: \">"+one.get(j).getJk()+"</th>\n");
                sb.append("    </rows>\n");
            }
            //集装箱-场桥
            for (int j = 0;j < yardCraneObject.size();j++) {
                sb.append("     <rows>\n");
                sb.append("           <th name=\"对象编码: \">"+yardCraneObject.get(j).getCode()+"</th>\n");
                sb.append("           <th name=\"对象名称: \">"+yardCraneObject.get(j).getMc()+"</th>\n");
                sb.append("           <th name=\"状态: \">"+yardCraneObject.get(j).getZt()+"</th>\n");
                sb.append("           <th name=\"作业内容: \">"+yardCraneObject.get(j).getZynr()+"</th>\n");
                sb.append("      </rows>\n");
            }
            //集装箱-泊位
            for (int j = 0;j < containerBerthObjects.size();j++) {
                sb.append("    <rows>\n");
                sb.append("		 <th name=\"对象编号: \">"+containerBerthObjects.get(j).getCode()+"</th>\n");
                sb.append("		 <th name=\"对象名称: \">"+containerBerthObjects.get(j).getMc()+"</th>\n");
                sb.append("		 <th name=\"状态: \">"+containerBerthObjects.get(j).getZt()+"</th>\n");
                sb.append("		 <th name=\"船名: \">"+containerBerthObjects.get(j).getCmc()+"</th>\n");
                sb.append("		 <th name=\"航次: \">"+containerBerthObjects.get(j).getHc()+"</th>\n");
                sb.append("		 <th name=\"船舶公司: \">"+containerBerthObjects.get(j).getCbgs()+"</th>\n");
                sb.append("		 <th name=\"靠泊时间: \">"+containerBerthObjects.get(j).getKbsj()+"</th>\n");
                sb.append("		 <th name=\" \">"+" "+"</th>\n");
                sb.append("		 <th name=\"待停靠船舶: \">"+containerBerthObjects.get(j).getCm()+"</th>\n");
                //sb.append("		 <th name=\"入港时间: \">"+containerBerthObjects.get(j).getRgsj()+"</th>\n");
                //sb.append("		 <th name=\"计划靠泊时间: \">"+containerBerthObjects.get(j).getJhkbsj()+"</th>\n");
                //sb.append("		 <th name=\"作业开始时间: \">"+containerBerthObjects.get(j).getZykssj()+"</th>\n");
                //sb.append("		 <th name=\"作业结束时间: \">"+containerBerthObjects.get(j).getZyjssj()+"</th>\n");
                sb.append("    </rows>\n");
            }
            //集装箱-岸桥
            for (int j = 0;j < quayCraneObject.size();j++) {
                sb.append("     <rows>\n");
                sb.append("            <th name=\"对象编码: \">"+quayCraneObject.get(j).getCode()+"</th>\n");
                sb.append("            <th name=\"对象名称: \">"+quayCraneObject.get(j).getMc()+"</th>\n");
                sb.append("            <th name=\"状态: \">"+quayCraneObject.get(j).getZt()+"</th>\n");
                sb.append("            <th name=\"作业内容: \">"+quayCraneObject.get(j).getZynr()+"</th>\n");
                sb.append("      </rows>\n");
            }

            //件散货-泊位
            List<NeobulkBerthObject> neobulkBerthObject;
            //件散货-堆场
            List<NeobulkYard> allNeobulkYard;
            try{
                neobulkBerthObject = neobulkBerthObjectService.findAllJsh();
                allNeobulkYard = neobulkYardService.findAllJsh();
            }catch(Exception e){
                neobulkBerthObject = neobulkBerthObjectService.findAllDc();
                allNeobulkYard = neobulkYardService.findAllDc();
            }
            //件散货-堆场
            for (int j = 0;j < allNeobulkYard.size();j++) {
                sb.append("    <rows>\n");
                sb.append("		 <th name=\"对象编码: \">"+allNeobulkYard.get(j).getCode()+"</th>\n");
                sb.append("		 <th name=\"对象名称: \">"+allNeobulkYard.get(j).getMc()+"</th>\n");
                sb.append("		 <th name=\"吨数: \">"+allNeobulkYard.get(j).getDs()+"</th>\n");
                sb.append("		 <th name=\"货物类型: \">"+allNeobulkYard.get(j).getHwlx()+"</th>\n");
                sb.append("    </rows>\n");
            }
            //件散货-泊位
            for (int j = 0;j < neobulkBerthObject.size();j++) {
                sb.append("    <rows>\n");
                sb.append("		    <th name=\"对象编码: \">"+neobulkBerthObject.get(j).getCode()+"</th>\n");
                sb.append("		    <th name=\"名称: \">"+neobulkBerthObject.get(j).getMc()+"</th>\n");
                sb.append("		    <th name=\"状态: \">"+neobulkBerthObject.get(j).getZt()+"</th>\n");
                sb.append("		    <th name=\"船名称: \">"+neobulkBerthObject.get(j).getCmc()+"</th>\n");
                sb.append("		    <th name=\"航次: \">"+neobulkBerthObject.get(j).getHc()+"</th>\n");
                sb.append("		    <th name=\"船舶公司: \">"+neobulkBerthObject.get(j).getCbgs()+"</th>\n");
                sb.append("		    <th name=\"入港时间: \">"+neobulkBerthObject.get(j).getRgsj()+"</th>\n");
                sb.append("		    <th name=\"靠泊时间: \">"+neobulkBerthObject.get(j).getKbsj()+"</th>\n");
                sb.append("		    <th name=\"计划靠泊时间: \">"+neobulkBerthObject.get(j).getJhkbsj()+"</th>\n");
                sb.append("		    <th name=\"作业开始时间: \">"+neobulkBerthObject.get(j).getZykssj()+"</th>\n");
                sb.append("		    <th name=\"作业结束时间: \">"+neobulkBerthObject.get(j).getZyjssj()+"</th>\n");
                sb.append("    </rows>\n");
            }
            //两江仓储-仓库
            try{
                List<WarehouseObject> allWarehouse = warehouseObjectService.findAllCc();
                for (int j = 0;j < allWarehouse.size();j++) {
                    sb.append("    <rows>\n");
                    sb.append("		    <th name=\"对象编码: \">"+allWarehouse.get(j).getCode()+"</th>\n");
                    sb.append("		    <th name=\"对象名称: \">"+allWarehouse.get(j).getMc()+"</th>\n");
                    sb.append("		    <th name=\"总库存: \">"+allWarehouse.get(j).getZkc()+"</th>\n");
                    sb.append("		    <th name=\"板材: \">"+allWarehouse.get(j).getBc()+"</th>\n");
                    sb.append("		    <th name=\"型材: \">"+allWarehouse.get(j).getXc()+"</th>\n");
                    sb.append("		    <th name=\"建材: \">"+allWarehouse.get(j).getJc()+"</th>\n");
                    sb.append("		    <th name=\"优钢: \">"+allWarehouse.get(j).getYg()+"</th>\n");
                    sb.append("		    <th name=\"卷材: \">"+allWarehouse.get(j).getJcl()+"</th>\n");
                    sb.append("		    <th name=\"管材: \">"+allWarehouse.get(j).getGc()+"</th>\n");
                    sb.append("		    <th name=\"有色金属: \">"+allWarehouse.get(j).getYsjs()+"</th>\n");
                    sb.append("		    <th name=\"容器板: \">"+allWarehouse.get(j).getRqb()+"</th>\n");
                    sb.append("		    <th name=\"其它: \">"+allWarehouse.get(j).getQt()+"</th>\n");
                    sb.append("    </rows>\n");
                }
            } catch(Exception e){
                List<com.harbour.ws.domain.dc.WarehouseObject> allWarehouse = warehouseObjectService.findAllDc();
                for (int j = 0;j < allWarehouse.size();j++) {
                    sb.append("    <rows>\n");
                    sb.append("		    <th name=\"对象编码: \">"+allWarehouse.get(j).getCode()+"</th>\n");
                    sb.append("		    <th name=\"对象名称: \">"+allWarehouse.get(j).getMc()+"</th>\n");
                    sb.append("		    <th name=\"总库存: \">"+allWarehouse.get(j).getZkc()+"</th>\n");
                    sb.append("    </rows>\n");
                }
            }
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JZX-S02-0049"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"22"+"</th>\n");
            sb.append("		  <th name=\"使用率: \">"+"23%"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC1-0"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC1-0"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC1-1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC1-1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC1-2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC1-2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC1-3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC1-3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-4"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-4"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-5"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-5"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ1-6"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ1-6"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-4"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-4"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-5"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-5"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-6"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-6"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-7"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-7"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTJ2-8"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路进口皮带-BTJ2-8"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ4"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ4"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ5"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ5"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ6"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ6"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BDQ7"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"堆取料皮带-BDQ7"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTC1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路出口皮带-BTC1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTC2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路出口皮带-BTC2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTC3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路出口皮带-BTC3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTC4"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路出口皮带-BTC4"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BTC5"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"铁路出口皮带-BTC5"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"1,0,1"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC2-1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC2-1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC2-2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC2-2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC2-3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC2-3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC3-1"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC3-1"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC3-2"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC3-2"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J03-BSC3-3"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"水路出口皮带BSC3-3"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"颜色: \">"+"0,1,0"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K129"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0002"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"2号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K129"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0003"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"3号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"null"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"null"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0004"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"4号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K119"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0005"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"5号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"null"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"null"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0006"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"6号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K119"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0007"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"7号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K119"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0008"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"8号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"null"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"null"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0009"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"9号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K219"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0010"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"10号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K519"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0011"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"11号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"K2319"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0012"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"12号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"-"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"TL-J07-0013"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"13号铁路"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"停靠火车: \">"+"null"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"null"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J10-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#卸船机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0002"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"2#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0003"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"3#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0004"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"4#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0005"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"5#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0006"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"6#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J09-0007"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"7#门机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J06-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#装船机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J06-0002"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"2#装船机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J06-0003"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"3#装船机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J05-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#翻车机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J04-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#装载机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J02-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#场桥"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J02-0002"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"2#场桥"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J02-0003"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"3#场桥"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J02-0004"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"4#场桥"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J02-0005"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"5#场桥"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0001"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"1#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0002"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"2#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"使用中"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0003"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"3#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("    <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0004"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"4#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0005"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"5#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0006"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"6#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"JSH-J11-0007"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"7#斗轮机"+"</th>\n");
            sb.append("		  <th name=\"状态: \">"+"空闲"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"-"+"</th>\n");
            sb.append("    </rows>\n");
        } else if("move".equals(type)) {
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"00023"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"张国伟"+"</th>\n");
            sb.append("		  <th name=\"类型: \">"+"1"+"</th>\n");
            sb.append("		  <th name=\"职务: \">"+"修理工"+"</th>\n");
            sb.append("		  <th name=\"电话: \">"+"15612674678"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"场桥修理"+"</th>\n");
            sb.append("		  <th name=\"经度: \">"+"106.786274"+"</th>\n");
            sb.append("		  <th name=\"纬度: \">"+"29.617683"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"00024"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"王建"+"</th>\n");
            sb.append("		  <th name=\"类型: \">"+"1"+"</th>\n");
            sb.append("		  <th name=\"职务: \">"+"修理工"+"</th>\n");
            sb.append("		  <th name=\"电话: \">"+"15612345679"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"场桥修理"+"</th>\n");
            sb.append("		  <th name=\"经度: \">"+"106.791247"+"</th>\n");
            sb.append("		  <th name=\"纬度: \">"+"29.616733"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"100024"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"渝B.12ASD"+"</th>\n");
            sb.append("		  <th name=\"类型: \">"+"2"+"</th>\n");
            sb.append("		  <th name=\"司机: \">"+"曹易"+"</th>\n");
            sb.append("		  <th name=\"电话: \">"+"15612346429"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("		  <th name=\"经度: \">"+"106.776734"+"</th>\n");
            sb.append("		  <th name=\"纬度: \">"+"29.620729"+"</th>\n");
            sb.append("    </rows>\n");
            sb.append("     <rows>\n");
            sb.append("		  <th name=\"对象编码: \">"+"100026"+"</th>\n");
            sb.append("		  <th name=\"对象名称: \">"+"渝B.12ASE"+"</th>\n");
            sb.append("		  <th name=\"类型: \">"+"2"+"</th>\n");
            sb.append("		  <th name=\"司机: \">"+"王领"+"</th>\n");
            sb.append("		  <th name=\"电话: \">"+"15612345645"+"</th>\n");
            sb.append("		  <th name=\"工作内容: \">"+"货物运输"+"</th>\n");
            sb.append("		  <th name=\"经度: \">"+"106.78976"+"</th>\n");
            sb.append("		  <th name=\"纬度: \">"+"29.622801"+"</th>\n");
            sb.append("    </rows>\n");
        }
        sb.append("  </tableList>\n");
        sb.append("</Data>\n");
        return sb.toString();
    }
}
